Traceback (most recent call last):
  File "../exps/si_test.py", line 25, in <module>
    sampling_op = [['c_reparam', 'gste'], ['c_reparam'], ['l_reparam'], ['l_reparam'], ['l_reparam', 'ste']][task_id]
IndexError: list index out of range
