Traceback (most recent call last):
  File "../exps/mter_test.py", line 98, in <module>
    'data_multiplier': datam} 
NameError: name 'datam' is not defined
