2019-09-07 18:11:42.483419: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-09-07 18:11:42.682825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:85:00.0
totalMemory: 11.92GiB freeMemory: 11.84GiB
2019-09-07 18:11:42.682947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-09-07 18:11:45.314718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-07 18:11:45.314844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-09-07 18:11:45.314922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-09-07 18:11:45.316163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11477 MB memory) -> physical GPU (device: 0, name: Tesla K40c, pci bus id: 0000:85:00.0, compute capability: 3.5)
Traceback (most recent call last):
  File "../exps/mter_test.py", line 160, in <module>
    result_dicts.append(experiment.train(rnn_config, labelled_data_config, training_config, pretrain_config, info_config))
  File "../src/experiment.py", line 44, in train
    set_rnn_config(rnn_config)
  File "../src/global_variable.py", line 33, in set_rnn_config
    raise Exception('Train config set more than once')
Exception: Train config set more than once
