Traceback (most recent call last):
  File "../exps/test.py", line 127, in <module>
    task_id=task_id)
  File "/clusterFS/home/student/kopp13/VarRNN/src/network_gpu/experiment.py", line 40, in __init__
    self.create_nn(self.gpu_dataset, data_config)
  File "/clusterFS/home/student/kopp13/VarRNN/src/network_gpu/experiment.py", line 43, in create_nn
    self.rnn = RNN(gpu_dataset)
  File "/clusterFS/home/student/kopp13/VarRNN/src/network_gpu/rnn.py", line 68, in __init__
    self.create_bayesian_training_graph(DatasetKeys.TR_SET)
  File "/clusterFS/home/student/kopp13/VarRNN/src/network_gpu/rnn.py", line 271, in create_bayesian_training_graph
    vfe, kl, elogl, acc = self.create_rnn_graph(key, self.rnn_config)
  File "/clusterFS/home/student/kopp13/VarRNN/src/network_gpu/rnn.py", line 182, in create_rnn_graph
    self.gpu_datasets.data_config.ds_configs.minibatch_size *
AttributeError: 'RNN' object has no attribute 'gpu_datasets'
